### PR TITLE
Fix support for Taxonomies and Taxons

### PR DESCRIPTION
**Pull request by docelic**
The following query now works:

```
{
  taxonomies {
    name
    taxons {
      id
      name
      products {
        name
      }
    }
  }
}
```

Tests will be added later when the test environment becomes
operational (currently it errors out on being unable to find
rs-rails and rubocop-rs).

### CODE REVIEW

**Comment by docelic** [comment]
Probably a suboptimal thing in this patch is that I've lost the "connection" part on the products and taxons. I'll make another simple PR with just the good parts, and this PR can be closed.

**Comment by dhonig** [comment]
Awesome i was going to add this over the weekend. Given the primordial state of the gem lets add a test and merge it

**Comment by docelic** [comment]
@dhonig - right, I didn't add a test because when I try to run the tests it fails on not finding rs-rails and rubocop-rs gems. Also, if/when I just commented those, some other error came up.

If you guys could write a test for it (and as part of it fix or confirm that the test environment works), it would allow me to learn from it and submit further code with tests included myself.

Thanks!

**Comment by dhonig** [comment]
Ok ill pick this up tomorrow and add a testing guide to readme.md

**Comment by docelic** [comment]
@dhonig If you don't have enough time, how about merging this and #11, and once that is done I can figure out and/or fix the way test suite is supposed to work and submit the missing tests? It would be no problem at all.

**Comment by dhonig** [comment]
@docelic   This branch now has conflicts.   If we can get those addresses then I'll merge it.  I should have time this week, just things come up.  As far as testing there are several examples already, they more or less follow the same pattern as: https://medium.com/@cam_irmas/happy-hour-testing-phoenix-absinthe-graphql-apis-46f5bb2c0379  

That example is in Elixir but it shows me that others aren't doing anything more or less as far as testing.   It looks like everyone is testing the entire GraphQL message.  The only other things I can can think of as far as testing involve using spies, mocks, etc and this doesn't seem like it adds any value since it would only test the invocation of the method...
 Another approach would be the one taken by VCR with rest....But I'm fine with the manual way for now.  If the GraphQL messages get really big then we can look into a more VCR like approach.

**Comment by docelic** [comment]
Awesome, I will resolve the conflicts within today and submit a new commit. Thanks!

**Comment by docelic** [comment]
Hey @dhonig here it is. I have resolved the conflicts and from what I see, it applies cleanly now. Please try again. If it works, I am continuing with the work on adding the tests as the first next thing. Thanks!

**Comment by dhonig** [comment]
squashed and merged

**Pull request merged**
